config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'dashboard#index'
  resources :customers, only: [:index]
  get "angular_test" => "angular_test#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/customer_search_term.rb
class CustomerSearchTerm
  attr_reader :where_clause, :where_args, :order

  def initialize(search_term)
    search_term = search_term.downcase
    @where_clause = ""
    @where_args = {}
    if search_term =~ /@/
      build_for_email_search(search_term)
    else
      build_for_name_search(search_term)
    end
  end

  def build_for_name_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(search_term)
    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(search_term)
    @order = "last_name asc"
  end

  def build_for_email_search(search_term)
    @where_clause << case_insensitive_search(:first_name)
    @where_args[:first_name] = starts_with(extract_name(search_term))
    @where_clause << " OR #{case_insensitive_search(:last_name)}"
    @where_args[:last_name] = starts_with(extract_name(search_term))
    @where_clause << " OR #{case_insensitive_search(:email)}"
    @where_args[:email] = search_term
    @order = "lower(email) = " +
        ActiveRecord::Base.connection.quote(search_term) +
        " desc, last_name asc"
  end

  def starts_with(search_term)
    search_term + "%"
  end

  def case_insensitive_search(field_name)
    "lower(#{field_name}) like :#{field_name}"
  end

  def extract_name(email)
    email.gsub(/@.*$/, '').gsub(/[0-9]+/, '')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  PAGE_SIZE = 10

  def index
    @page = (params[:page] || 0).to_i
    if params[:keywords].present?
      @keywords = params[:keywords]
      customer_search_term = CustomerSearchTerm.new(@keywords)
      @customers = Customer.where(
          customer_search_term.where_clause,
          customer_search_term.where_args).
          order(customer_search_term.order).
          offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
    else
      @customers = []
    end
    respond_to do |format|
      format.html {}
      format.json { render json: @customers }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/helpers/angular_test_helper.rb
module AngularTestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
  <header>
    <h1 ng-if="name">Hello, {{name}}</h1>
  </header>
  <section>
    <form class="form-inline">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control"
               name="name"
               type="text"
               placeholder="Enter your name"
               autofocus
               ng-model="name">
      </div>
    </form>
  </section>
</article>

app/views/customers/_pager.html.erb
<!--<nav>-->
<!--<ul class="pager">-->
<!--<li class="previous <%#= page == 0 ? 'disabled' : '' %>">-->
<!--<%#= link_to_if page > 0, "&larr; Previous".html_safe, customers_path(:keywords => keywords, :page => page - 1) %>-->
<!--</li>-->
<!--<li class="next">-->
<!--<%#= link_to "Next &rarr;".html_safe, customers_path(keywords: keywords, page: page + 1) %>-->
<!--</li>-->
<!--</ul>-->
<!--</nav>-->

<nav>
  <ul class="pager">
    <li class="previous">
      <a href="" ng-click="previousPage()">&larr; Previous</a>
    </li>
    <li class="next">
      <a href="" ng-click="nextPage()">Next &rarr;</a>
    </li>
  </ul>
</nav>

app/views/customers/index.html.erb
<header>
  <h1 class="h2">Customer Search</h1>
</header>
<!--<section class="search-form">-->
<!--<%#= form_for :customers, method: :get do |f| %>-->
<!--<div class="input-group input-group-lg">-->
<!--<%#= label_tag :keywords, nil, class: "sr-only" %>-->
<!--<%#= text_field_tag :keywords, nil, placeholder: "First Name, Last Name, or Email Address", class: "form-control input-lg" %>-->
<!--<span class="input-group-btn">-->
<!--<%#= submit_tag "Find Customers", class: "btn btn-primary btn-lg" %>-->
<!--</span>-->
<!--</div>-->
<!--<%# end %>-->
<!--</section>-->
<!--<section class="search-results">-->
<!--<header>-->
<!--<h1 class="h3">Results</h1>-->
<!--</header>-->
<!--<ol class="list-group">-->
<!--<%# @customers.each do |customer| %>-->
<!--<li class="list-group-item clearfix">-->
<!--<h3 class="pull-right">-->
<!--<small class="text-uppercase">Joined</small>-->
<!--<%#= l customer.created_at.to_date %>-->
<!--</h3>-->
<!--<h2 class="h3">-->
<!--<%#= customer.first_name %> <%#= customer.last_name %>-->
<!--<small><%#= customer.username %></small>-->
<!--</h2>-->
<!--<h4><%#= customer.email %></h4>-->
<!--</li>-->
<!--<%# end %>-->
<!--</ol>-->
<%#= render :partial => "pager", locals: {keywords: @keywords, page: @page} %>
<!--</section>-->
<!---->



<article ng-app="customers" ng-controller="CustomerSearchController">
  <section class="search-form">
    <form>
      <!--<div class="input-group input-group-lg">-->
      <!--<label for="keywords" class="sr-only">Keywords</label>-->
      <!--<input type="text" name="keywords" class="form-control input-lg" `placeholder="First Name, Last Name, or Email Address" ng-model="keywords">-->
      <!--<span class="input-group-btn">-->
      <!--<button class="btn btn-primary btn-lg" ng-click="search(keywords)">Find Customers</button>-->
      <!--</span>-->
      <!--</div>-->
      <label for="search.keywords" class="sr-only">Keywords</label>
      <input type="text"
             name="keywords"
             class="form-control input-lg"
             placeholder="First Name, Last Name, or Email Address"
             ng-change="search(keywords)"
             ng-model="keywords">
    </form>
    <h1 class="searchedFor" ng-if="searchedFor">
      <small>Searched for:</small>
      {{searchedFor}}
    </h1>
    <section class="search-results">
      <header>
        <h1 class="h3">Results</h1>
      </header>
      <%= render partial: "pager", locals: {keywords: @keywords, page: @page} %>
      <ol class="list-group">
        <li class="list-group-item clearfix"
            ng-repeat="customer in customers">
          <h3 class="pull-right">
            <small class="text-uppercase">Joined</small>
            {{ customer.created_at | date }}
          </h3>
          <h2 class="h3">
            {{ customer.first_name }} {{ customer.last_name }}
            <small>{{ customer.username }}</small>
          </h2>
          <h4>{{ customer.email }}</h4>
        </li>
      </ol>
      <%= render partial: "pager", locals: {keywords: @keywords, page: @page} %>
    </section>
  </section>
</article>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Welcome to Shine, <%= current_user.email %>
  </h1>

  <h2>
    We're using Rails <%= Rails.version %>
  </h2>
</header>
<section>
  <p>
    Future home of Shine's Dashboard
  </p>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shine</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<% if notice.present? %>
    <aside class="alert alert-info">
      <%= notice %>
    </aside>
<% end %>
<% if alert.present? %>
    <aside class="alert alert-danger">
      <%= alert %>
    </aside>
<% end %>
<%= yield %>

</body>
</html>